# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cf9637e668d03219fd1b7847984c670661a6acbb5092ab53fa1485dabd4393e4f57463510a4f422a6a88f38b2fb83a5f0d10d99b271ee9cc9ba48c83e5c66c9

test:
  secret_key_base: ca39431f493ba6a1a5a919129e3c12abea141d8746c7eda9152b2b2f94aca7792980c3c321c6f18671115573ecfcad33cb17a700242d481027e5abd0f4f64580

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 7c740f9a4a91b0c319c6b673111beff4b483fa8f9d84b74403b0be6bb13b2024111c1fffe15cd7e11b5eb7c2ccf5337635ede5620a839b06f8c23186b7efedf8
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
